language: python
python:
 - 3.5
before_install:
- pip install --upgrade pip
install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
script:
- coverage run --source='.' employeemanager/manage.py test staff.tests
after_success:
- bash <(curl -s https://codecov.io/bash)
